---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: linear
      mountPath: /linear
    - name: mirror
      mountPath: /mirror
    - name: striped
      mountPath: /striped
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 100M
  volumes:
  - name: linear
    persistentVolumeClaim:
      claimName: lvm-pvc-linear
  - name: mirror
    persistentVolumeClaim:
      claimName: lvm-pvc-mirror
  - name: striped
    persistentVolumeClaim:
      claimName: lvm-pvc-striped