---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-pvc-linear
  namespace: default
  annotations:
    csi-lvm.metal-stack.io/type: "linear"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-lvm
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-pvc-mirror
  namespace: default
  annotations:
    csi-lvm.metal-stack.io/type: "mirror"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-lvm
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-pvc-striped
  namespace: default
  annotations:
    csi-lvm.metal-stack.io/type: "striped"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-lvm
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-pvc-block
  namespace: default
  annotations:
    csi-lvm.metal-stack.io/type: "linear"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: csi-lvm
  resources:
    requests:
      storage: 10Mi