FROM ubuntu:20.04
RUN apt update \
 && apt install -y git curl \
 && curl -Lo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64 \
 && chmod +x /usr/local/bin/yq
