---
apiVersion: v1
kind: Pod
metadata:
  name: csi-enter-host
  namespace: csi-lvm
spec:
  containers:
  - command:
    - sleep 
    - "1000"
    image: metalstack/csi-lvm-provisioner
    imagePullPolicy: IfNotPresent
    name: csi-lvm-create
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /data/
      name: data
    - mountPath: /dev
      name: devices
  volumes:
  - hostPath:
      path: /tmp/csi-lvm
      type: DirectoryOrCreate
    name: data
  - hostPath:
      path: /dev
      type: DirectoryOrCreate
    name: devices
