name: Auto Generate

on:
  push:
    branches:
      - auto-generate/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "true"
        lfs: true
    - name: Render
      run: |
        make update
        make
    - name: Push
      run: |
        if ! git diff --exit-code; then
          git config --global user.name "auto-build"
          git config --global user.email "info@metal-stack.io"
          git add .
          git commit -m "Auto generate"
          git push
        fi
