---
name: Release Documentation

on:
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
          lfs: true
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.4.2
      - name: Install dependencies
        run: julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
      - name: Set release tag
        run: echo "::set-env name=RELEASE_VERSION::$(echo $GITHUB_REF | awk -F / '{print $3}')"
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.resolve(); include("docs/make.jl")'
